config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  get '/about' => 'static_pages#about'
  get '/.well-known/acme-challenge/:id' => 'static_pages#lets_encrypt'

  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :papers, only: [:show, :edit, :update] do
    resources :links, only: :destroy, shallow: true
  end

  resources :pins, only: [:create, :destroy]

  resources :lists, only: [:new, :create] do
    resources :references, only: [:show, :create, :destroy]
    resource :vote, controller: 'lists/votes', only: [:create, :destroy]
    resources :members, only: :destroy, controller: 'lists/members'
  end

  resources :references do
    resource :vote, controller: 'references/votes', only: [:create, :destroy]
  end

  resources :comments, only: [:create, :edit, :update, :destroy] do
    resource :vote, controller: 'comments/votes', only: [:create, :destroy]
  end

  scope ':username' do
    resources :lists, path: '/', except: [:new, :create], as: :user_lists, controller: 'users/lists'
    get ':user_list_id/:id' => 'references#show', as: :user_list_reference
  end

end

app/models/list.rb
class List < ApplicationRecord
  # Modules
  acts_as_taggable
  acts_as_votable

  # Attributes
  enum visibility: {private: 10, contributors: 20, public: 30}, _prefix: :visible_to
  enum participants: {private: 10, contributors: 20, public: 30}, _prefix: :accepts, _suffix: :contributions

  # Scopes
  default_scope { joins(:list_memberships).order(cached_votes_up: :desc, updated_at: :desc) }
  scope :publicly_visible, -> { where(visibility: :public).distinct }

  # Callbacks
  after_create ->{ list_memberships.find_or_create_by(list: self, user: user) }
  before_create :set_slug

  # Associations
  belongs_to :user
  has_and_belongs_to_many :homepages
  has_many :list_memberships, dependent: :destroy
  has_many :papers, through: :references
  has_many :references, dependent: :destroy
  has_many :members, through: :list_memberships, source: :user do
    def [] role
      where("list_memberships.role = ?", ListMembership.roles.fetch(role))
    end

    def add user, role: nil
      attrs = {list: @association.owner, user: user}
      attrs.merge!(role: role) if role
      ListMembership.create(attrs)
    end
  end

  # Validations
  validates :name,
            presence: true,
            uniqueness: {
              scope: :user,
              case_sensitive: false,
              message: "must be unique for lists you own."
            }
  validates_associated :list_memberships

  # Methods
  def owner
    members[:owner].first
  end

  def owner= user
    List.transaction do
      if (owner_membership = list_memberships.find_by(role: :owner))
        owner_membership.update_column(:role, :moderator)
      end

      list_memberships.find_or_create_by(user: user).update_column :role, :owner
    end
  end

  def to_slug
    self.name.downcase.gsub("'", '').scan(/[\p{N}\p{L}]{1,}/).join('-')
  end

  def set_slug
    self.slug = self.to_slug
  end

  def set_slug!
    self.update_column :slug, self.to_slug;
  end

  def to_param
    slug
  end
end

app/controllers/lists/members_controller.rb
class Lists::MembersController < ApplicationController
  before_action :ensure_current_user

  def destroy
    list = List.find params[:list_id]
    path = edit_user_list_path(list.user, list)
    current_membership = list.list_memberships.find_by user: current_user
    return unless current_membership

    member = User.find params[:id]
    removing_self = member == current_user

    unless current_membership.can_moderate? || removing_self
      return redirect_back(fallback_location: path, alert: 'You do not have permission to moderate this list')
    end

    list.members.delete member
    if removing_self
      return redirect_to(user_list_path(list.user, list), notice: "You are no longer a contributor to \"#{list.name}\"")
    else
      return redirect_back(fallback_location: path, notice: "\"#{member.username}\" is no longer a contributor")
    end
  end
end

app/controllers/lists/votes_controller.rb
class Lists::VotesController < ApplicationController
  before_action :ensure_current_user

  def create
    current_user.likes List.find(votable_params[:id])

    redirect_to :back
  end

  def destroy
    current_user.unlike List.find(votable_params[:id])

    redirect_to :back
  end

  private
    def votable_params
      params.permit(:id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :ensure_current_user, except: [:index]

  # GET /lists
  # GET /lists.json
  def index
    if current_user
      @pinned_lists = current_user.visible_lists.merge(current_user.homepage.lists.distinct)
      @unpinned_lists = current_user.visible_lists.where.not(id: @pinned_lists.pluck(:id))
    else
      @unpinned_lists = List.publicly_visible
    end
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.build(list_params)
    member = User.find_by username: params[:list].delete(:members)
    @list.list_memberships.build(user: member, role: :contributor) if member

    respond_to do |format|
      if @list.save
        current_user.homepage.lists << @list
        format.html { redirect_to user_list_path(@list.owner, @list), notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :description, :tag_list, :participants)
    end
end

app/controllers/users/lists_controller.rb
class Users::ListsController < ApplicationController
  before_action :ensure_current_user, except: [:index, :show]
  before_action :set_user
  before_action :set_list, except: :index
  before_action :ensure_editable, only: [:edit, :update]
  before_action :ensure_visible, only: :show

  def index
    @lists = @user.authored_lists.distinct
  end

  def show
    @references = @list.references.joins(:paper).order(params_sort_order)
  end

  def edit
  end

  def update
    member = User.find_by username: params[:list].delete(:members)
    params[:list].delete(:participants) unless current_user == @list.owner

    if member && current_user.can_moderate?(@list)
      @list.list_memberships.build(user: member, role: :contributor)
    end

    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_back(fallback_location: user_list_path(@list.user, @list), notice: 'List was successfully updated.') }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    unless current_user == @list.owner
      return redirect_back(fallback_location: root_path, alert: 'Only the list owner can delete a list.')
    end

    @list.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find_by 'LOWER(username) = ?', params[:username].downcase
    end

    def set_list
      @list = @user.owned_lists.find_by slug: params[:id]
      return redirect_back(fallback_location: root_path, alert: "List not found.") unless @list
    end

    def params_sort_order
      if params[:sort] == 'pub_date'
        'papers.published_at DESC NULLS LAST'
      else # default to ordering by votes first, then create date
        "cached_votes_up DESC, created_at ASC"
      end
    end

    def list_params
      params.require(:list).permit(:name, :description, :tag_list, :members, :participants)
    end

    def ensure_editable
      redirect_to(root_path) unless current_user

      unless current_user.can_edit? @list
        return redirect_back(
          fallback_location: root_path,
          alert: 'You must be a contributor to make changes to this list.'
        )
      end
    end

    def ensure_visible
      return if @list.visible_to_public?
      return redirect_back(fallback_location: root_path) unless current_user && current_user.can_view?(@list)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
  def current_user_can_moderate? list
    current_user && current_user.can_moderate?(list)
  end

  def current_user_can_edit? list
    current_user && current_user.can_edit?(list)
  end

  def current_user_can_view? list
    current_user && current_user.can_view?(list)
  end
end

app/views/lists/_add_reference.html.erb
<%= form_for list.references.build, html: {class: 'form-inline'} do |f| %>
  <%= f.hidden_field :list_id, value: list.id %>
  <div class="add-paper">
    <%= f.fields_for Paper.new do |p| %>
      <div class="form-group add-reference col-md-12">
        <%= p.hidden_field :locator_type, value: '', id: 'add_locator_type' %>
        <i>
          Or add a paper by
          <%= link_to "DOI", '#', id: "add-doi" %>,
          <%= link_to "Pubmed ID", '#', id: "add-pubmed" %>,
          or <%= link_to "URL", '#', id: "add-link" %>
        </i>
        <%= p.text_field  :locator_id,
                          placeholder: 'URL, DOI, or Pubmed',
                          class: "form-control hidden paper-locator input-sm",
                          disabled: true %>

        <%= p.text_field  :title,
                          placeholder: 'Required - Paper Title ex: Regulation of the Neural Circuitry of Emotion',
                          class: "form-control hidden paper-title input-sm",
                          disabled: true %>
        <div class="form-group">
          <%= f.submit "Submit",
                class: "btn btn-primary btn-xs hidden",
                id: 'add_locator_submit',
                disabled: !(list.accepts_public_contributions? || current_user_can_edit?(list)) %>
          <%= link_to "cancel", '#', id: "cancel-add-locator", class: "hidden" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/lists/_form.html.erb
<% url = if list.persisted? then user_list_path(list.owner, list) else lists_path end  %>

<%= form_for(list, url: url) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-horizontal">
    <div class="form-group">
      <%= f.label :name, class: "col-md-2 control-label" %>
      <div class="col-md-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "col-md-2 control-label" %>
      <div class="col-md-10">
        <%= f.text_area :description, class: "form-control", rows: 5 %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-2 control-label">
        <%= f.label :tag_list, 'Tags'%>
        <p><small>(separated by commas)</small></p>
      </div>
      <div class="col-md-10">
        <%= f.text_field :tag_list, value: list.tag_list.join(","), class: "form-control", placeholder: 'Ex: biology, chemistry, physics' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-2 control-label">
        <%= f.label :participants, 'List participants'%>
        <p><small>(who can add to this list?)</small></p>
      </div>
      <div class="col-md-10">
        <%= f.select :participants,
          options_for_select(
            [%w{Public public},%w{Contributors contributors}],
            list.participants
          ),
          {},
          {class: "form-control", disabled: list.persisted? && !(current_user == list.owner)} %>
      </div>
    </div>

    <% if list.persisted? %>
      <div class="form-group">
        <label class="col-md-2 control-label">List owner</label>
        <div class="col-md-10">
          <div class="form-control contributor-list">
            <%= link_to list.owner.username, user_lists_path(list.owner) %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">Current contributors</label>
        <div class="col-md-10">
          <% members = list.members.where.not(id: list.owner.id) %>
          <% if members.any? %>
            <% members.each do |member| %>
              <div class="form-control contributor-list">
                <%= link_to member.username, user_lists_path(member) %>
                <% if current_user_can_moderate?(list) || member == current_user %>
                  <%= link_to('Remove',
                        list_member_path(list.id, member.id),
                        class: "remove-member text-danger pull-right",
                        method: :delete) %>
                <% end %>
              </div>
            <% end %>
          <% else %>
            <div class="form-control">None</div>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :members, 'Add a contributor', class: "col-md-2 control-label"  %>
      <div class="col-md-10">
        <%
          if list.persisted?
            non_members = User.all - @list.members
            disable_contributors = !current_user.can_moderate?(list)
          else
            non_members = User.all - [current_user]
            disable_contributors = false
          end
        %>
        <%= f.select :members, non_members.map(&:username), {include_blank: 'None'}, {class: "form-control", disabled: disable_contributors}  %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit button_name, class: "btn btn-primary" %>
        <%= link_to 'cancel',
          if list.id then user_list_path(list.user, list) else root_path end
        %>
      </div>
    </div>
  </div>
<% end %>

app/views/lists/_list.erb
<div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-body">
      <% if user_signed_in? %>
        <div class="row">
          <div class="col-md-12">
            <%= render 'lists/toggle_pin', list: list %>
            <%= render 'votes/toggle_like', votable: list %>
            <small class="pull-right">
              <%= link_to 'Edit ', edit_list_path(list) %>
              <%= link_to ' Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %>
            </small>
          </div>
        </div>
      <% end %>
      <h2><%= link_to list.name, list %></h2>
      <p><%= list.description %></p>
      <small>Tags:<i><%= list.tag_list %></i></br></small>
    </div>
  </div>
</div>

app/views/lists/_list.html.erb
<div class="col-md-3 list-card">
  <div class="panel panel-default">
    <div class="panel-body">
      <% if user_signed_in? %>
        <div class="row">
          <div class="col-md-12">
            <%= render 'lists/toggle_pin', list: list %>
            <%= render 'votes/toggle_like', votable: list %>
            <% if current_user.can_edit? list %>
              <small class="pull-right">
                <%= link_to 'Edit ', edit_user_list_path(list.owner, list) %>
              </small>
            <% end %>
          </div>
        </div>
      <% end %>
      <h2>
        <%= link_to list.name, user_list_path(list.owner, list) %><br>
        <small> by <%= link_to list.owner.username, user_lists_path(list.owner) %></small>
      </h2>
      <p><%= truncate(list.description, length: 400, separator: ' ') %></p>
      <small>Tags:<i><%= list.tag_list %></i></br></small>
    </div>
  </div>
</div>

app/views/lists/_toggle_pin.html.erb
<% if current_user.homepage.lists.include? list %>
  <%= link_to button_tag('Unpin', class: "btn btn-default btn-sm pull-left pin active"), pin_path(list), method: :delete %>
<% else %>
  <%= form_tag pins_path do %>
    <%= text_field_tag 'id', list.slug, hidden: true %>
    <%= submit_tag 'Pin', class: "btn btn-default btn-sm pull-left pin" %>
  <% end %>
<% end %>

app/views/lists/index.html.erb
<%
  @title = 'Home'
  @full_width = true
%>

<% if @pinned_lists.present? %>
  <div class="row">
    <div class="col-md-12">
      <h1>Pinned Lists</h1>
      <%= link_to 'Create New List', new_list_path %>
    </div>
  </div>

  <div class="cards row">
    <%= render @pinned_lists %>
  </div>
<% end %>

<% if @unpinned_lists.present? %>
  <div class="row">
    <div class="col-md-12">
      <h1>Lists</h1>
      <%= link_to 'Create New List', new_list_path %>
    </div>
  </div>

  <div class="cards row">
    <%= render @unpinned_lists %>
  </div>
<% end %>

app/views/lists/new.html.erb
<h2>New List</h2>

<%= render 'form', list: @list, button_name: "Create List" %>