config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  get '/about' => 'static_pages#about'
  get '/.well-known/acme-challenge/:id' => 'static_pages#lets_encrypt'

  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :papers, only: [:show, :edit, :update] do
    resources :links, only: :destroy, shallow: true
  end

  resources :pins, only: [:create, :destroy]

  resources :lists, only: [:new, :create] do
    resources :references, only: [:show, :create, :destroy]
    resource :vote, controller: 'lists/votes', only: [:create, :destroy]
    resources :members, only: :destroy, controller: 'lists/members'
  end

  resources :references do
    resource :vote, controller: 'references/votes', only: [:create, :destroy]
  end

  resources :comments, only: [:create, :edit, :update, :destroy] do
    resource :vote, controller: 'comments/votes', only: [:create, :destroy]
  end

  scope ':username' do
    resources :lists, path: '/', except: [:new, :create], as: :user_lists, controller: 'users/lists'
    get ':user_list_id/:id' => 'references#show', as: :user_list_reference
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  has_closure_tree order: 'sort_order'
  acts_as_votable

  validates :content, presence: true

  def self_and_sibling_ids
    self.sibling_ids + [self.id]
  end

  def order_siblings
    Comment
      .where(id: self_and_sibling_ids)
      .order(cached_votes_up: :desc, created_at: :asc)
      .each_with_index {|comment,i| comment.update_column :sort_order, i}
  end
end

app/controllers/comments/votes_controller.rb
class Comments::VotesController < ApplicationController
  before_action :ensure_current_user
  before_action :set_comment

  def create
    current_user.likes @comment
    @comment.order_siblings

    redirect_to :back
  end

  def destroy
    current_user.unlike @comment
    @comment.order_siblings

    redirect_to :back
  end

  private
    def votable_params
      params.permit(:id)
    end

    def set_comment
      @comment = Comment.find(votable_params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :ensure_current_user
  before_action :set_comment, only: [:edit, :update, :destroy]

  # GET /lists/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js do
          reference = @comment.root.commentable
          is_top_level = !!@comment.commentable

          if is_top_level
            render('references/comments/create.js.erb', locals: { reference: reference })
          else
            render('comments/create.js.erb', locals: { reference: reference })
          end
        end
      else
        format.html { redirect_to :back }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    unless @comment.user == current_user
      flash[:alert] = "You do not have permission to edit this comment"
      return redirect_back(fallback_location: user_list_path(list.owner, list))
    end

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to :back, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
        format.js { render 'update.js.erb', locals: {reference: @comment.root.commentable} }
      else
        format.html { redirect_to :back, notice: 'Comment was not updated.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    reference = @comment.root.commentable
    list = reference.list

    respond_to do |format|
      if current_user.can_moderate?(list) || @comment.user == current_user
        @comment.destroy
        format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
        format.js { render 'destroy.js.erb', locals: {reference: reference} }
      else
        flash[:alert] = 'You do not have permission to moderate this list.'

        format.html { redirect_back fallback_location: user_list_path(list.owner, list) }
        format.js { ajax_redirect_to(user_list_path(list.owner, list)) }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :parent_id, :commentable_type, :commentable_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments, list)
    comments.map do |comment, nested_comments|
      render 'comments/comment', comment: comment, list: list do
        content_tag(
          :div,
          comments_tree_for(nested_comments, list),
          class: "comments",
          'data-commentable-id' => comment.id
        )
      end
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>" >
  <p class="text-muted">
    <%= if comment.created_at == comment.updated_at then 'Added by' else 'Updated by' end %>
    <strong><%= link_to comment.user.username, user_lists_path(comment.user.username) %></strong> on <%= l(comment.updated_at, format: '%B, %d %Y %H:%M:%S') %>
  </p>
  <% comment_content = wrap_on_line_breaks comment.content %>
  <%= content_tag(:span, comment_content, class: "content") %>
  <ul>
    <li><%= render 'votes/toggle_like', votable: comment %></li>
    <li><%= (link_to 'reply', "#", class: 'toggle-reply btn btn-link btn-xs', 'data-parent-comment-id' => comment.id) if current_user %></li>
    <% if current_user == comment.user %>
      <li><%= link_to 'edit', edit_comment_path(comment), remote: true, class: "edit-comment btn btn-link btn-xs" %></li>
      <li><%= link_to 'delete', comment_path(comment), remote: true, class: "text-danger small", method: :delete %><li>
    <% elsif current_user_can_moderate?(list) %>
      <li><%= link_to 'delete', comment_path(comment), remote: true, class: "text-danger small", method: :delete %><li>
    <% end %>
  </ul>
  <%= render('comments/form', comment: comment.children.build, hidden: true) if current_user %>

  <%= yield %>
</div>

app/views/comments/_form.html.erb
<% hidden ||= false %>

<%= form_for comment, html: {class: "comment-reply #{'hidden' if hidden}"}, remote: true do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: 'form-control comment-box', placeholder: 'Write a reply...' %>
  </div>
  <%= f.hidden_field :parent_id, value: comment.parent_id %>
  <%= f.hidden_field :commentable_type, value: comment.commentable_type %>
  <%= f.hidden_field :commentable_id, value: comment.commentable_id %>
  <div class="form-group">
    <%= submit_tag "Submit", class: "btn btn-primary btn-xs" %>
    <%= link_to 'cancel', '#', class: 'cancel-link cancel-comment-form hidden' %>
  </div>
<% end %>

app/views/comments/create.js.erb
<%
  comment_and_comments_container = render('comments/comment', comment: @comment) do
    render('form', comment: @comment.children.build)
    content_tag(:div, '', class: 'comments', 'data-commentable-id' => @comment.id)
  end
%>

commentsContainer = $("div#comment-<%= @comment.parent_id %> > .comments");
commentsContainer.prepend("<%= escape_javascript(comment_and_comments_container) %>");
$('#comment-<%= @comment.parent_id %> > form').hide();

commentsCountSpan = $("span#comments-count-<%= reference.id %>");
commentsCount = parseInt(commentsCountSpan.text());
commentsCountSpan.text(parseInt(commentsCount) + 1);

app/views/comments/cud.js.erb
$("#comments-<%= @reference.id %>").html("<%= escape_javascript(render 'papers/comments', reference: @reference) %>");
$("li#comments-tab-<%= @reference.id %>").html("<%= escape_javascript(render 'papers/comments_tab', reference: @reference) %>");
$('.toggle-reply').on('click', function(e) {
  e.preventDefault();
  $(e.target).parents("ul").next('.comment-reply').toggleClass('hidden');
});

app/views/comments/destroy.js.erb
deletedComments = $("#comment-<%= @comment.id %>").find(".comment").length + 1;
$("#comment-<%= @comment.id %>").remove();

commentsCountSpan = $("span#comments-count-<%= reference.id %>");
commentsCount = parseInt(commentsCountSpan.text());
commentsCountSpan.text(parseInt(commentsCount - deletedComments));

<%= render 'layouts/flash_messages', flash: {notice: 'Comment deleted.'} %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment, hidden: false %>

<%= link_to 'Show', @comment %> | <%= link_to 'Back', comments_path %>

app/views/comments/edit.js.erb
newForm = "<%= escape_javascript(render 'form', comment: @comment, hidden: false) %>"
commentContent = $("#comment-<%= @comment.id %> > .content");
commentContent.data("undo-form", commentContent.html())
editLink = $("#comment-<%= @comment.id %>").find("a.edit-comment").first()
editLink.parent('li').toggleClass('hidden', true);

commentContent.html(newForm);
cancelLink = commentContent.find(".cancel-comment-form")
cancelLink.toggleClass('hidden', false);

app/views/comments/update.js.erb
commentContent = $("#comment-<%= @comment.id %> > .content")
commentContent.html("<%= wrap_on_line_breaks @comment.content %>")
editLink = $("#comment-<%= @comment.id %>").find("a.edit-comment").first()
editLink.parent('li').toggleClass('hidden', false);