config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  get '/about' => 'static_pages#about'
  get '/.well-known/acme-challenge/:id' => 'static_pages#lets_encrypt'

  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :papers, only: [:show, :edit, :update] do
    resources :links, only: :destroy, shallow: true
  end

  resources :pins, only: [:create, :destroy]

  resources :lists, only: [:new, :create] do
    resources :references, only: [:show, :create, :destroy]
    resource :vote, controller: 'lists/votes', only: [:create, :destroy]
    resources :members, only: :destroy, controller: 'lists/members'
  end

  resources :references do
    resource :vote, controller: 'references/votes', only: [:create, :destroy]
  end

  resources :comments, only: [:create, :edit, :update, :destroy] do
    resource :vote, controller: 'comments/votes', only: [:create, :destroy]
  end

  scope ':username' do
    resources :lists, path: '/', except: [:new, :create], as: :user_lists, controller: 'users/lists'
    get ':user_list_id/:id' => 'references#show', as: :user_list_reference
  end

end

app/models/paper.rb
class Paper < ApplicationRecord
  attr_accessor :locator_id, :locator_type

  acts_as_taggable
  acts_as_taggable_on :biases, :methodologies

  has_and_belongs_to_many :authors
  has_many :lists, through: :references
  has_many :references, dependent: :destroy
  has_many :links, dependent: :destroy
  has_many :api_import_responses, dependent: :destroy

  accepts_nested_attributes_for :authors, reject_if: proc { |attributes| attributes['family_name'].blank? }
  accepts_nested_attributes_for :links
  validates_associated :links
  validates :title, presence: true
  validate :allowed_biases, :allowed_methodologies

  before_save :downcase_name

  def downcase_name
    # This needs to be fixed - either we require a publication name or we stop downcasing
    self.publication.try :downcase!
  end

  def allowed_biases
	  invalid_biases = bias_list - valid_biases
	  invalid_biases.each {|b| errors.add(b, 'is not a supported bias') }
	end

  def allowed_methodologies
    invalid_methodologies = methodology_list - valid_methodologies
    invalid_methodologies.each {|b| errors.add(b, 'is not a supported methodology') }
  end

  def valid_biases
    [
      'selection',
      'performance',
      'detection',
      'attrition',
      'reporting',
      'small sample size'
    ]
  end

  def valid_methodologies
    [
      'meta-analysis',
      'systematic review',
      'randomized control trial',
      'quasi-experiment',
      'cohort',
      'case-control',
      'cross-sectional survey',
      'case report'
    ]
  end

  # Skips validations, fallthrough to autosave methods for easy import
  def validate_associated_records_for_authors; true; end
  def validate_associated_records_for_links; true; end

  def autosave_associated_records_for_authors
    self.authors = authors.map do |author|
      Author.find_or_create_by given_name: author.given_name, family_name: author.family_name
    end
  end

end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper
  before_action :ensure_current_user, except: :show

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/1/edit
  def edit
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_back(fallback_location: root_path, notice: 'Paper was successfully updated.') }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { redirect_back(fallback_location: root_path, alert: 'Paper failed to update') }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(
        :title, :abstract, :doi, :pubmed_id, :published_at, :publication,
        :tag_list,
        bias_list: [],
        methodology_list: [],
        links_attributes: [:id, :url],
        authors_attributes: [:id, :given_name, :family_name])
    end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_abstract.html.erb
<% paper = reference.paper %>
<% list = reference.list %>

<% if paper.abstract.present? %>
  <div class='edit-abstract' id="edit-abstract-<%=reference.id%>">
    <i class='help-block'>
      <% if paper.abstract_editable %>
        This abstract is user generated and can be
        <% if current_user_can_edit?(list) || (current_user && list.accepts_public_contributions?) %>
          <%= link_to 'edited', '#', class: "edit-abstract" %>
        <% else %>
          edited by contributors
        <% end %>
      <% else %>
        This abstract was imported and cannot be edited
      <% end %>
    </i>
    <%= wrap_on_line_breaks paper.abstract %>
  </div>
  <div class='abstract-form hidden'>
    <%= render('papers/abstract_form', paper: paper) %>
  </div>
<% elsif current_user_can_edit?(list) || (current_user && list.accepts_public_contributions?) %>
  <b>No abstract found, you can add one:</b>
  <%= render 'papers/abstract_form', paper: paper %>
<% else %>
  No abstract found.  Abstracts may only be added by contributors.
<% end %>

app/views/papers/_detail_wells.html.erb
<div class="collapse paper-detail well" id="abstract-<%= reference.id %>">
  <%= render 'papers/abstract', reference: reference %>
</div>

<div class="collapse paper-detail well" id="details-<%= reference.id %>">
  <%= render 'papers/links', reference: reference %>
</div>

<div class="paper-detail well collapse <%= "in" if show_comments %>" id="comments-<%= reference.id %>">
  <%= render 'references/comments', reference: reference %>
</div>

app/views/papers/_form.html.erb
<%= form_for(paper) do |f| %>
  <% if paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-horizontal">

    <div class="form-group">
      <%= f.label :title, class: "col-md-2 control-label" %>
      <div class="col-md-10">
        <%= f.text_area :title, class: "form-control"  %>
      </div>
    </div>

    <%= f.fields_for :authors, paper.authors do |a| %>
      <div class="form-group">
        <%= a.label :given_name, 'Author Given Name', class: "col-md-2 control-label" %>
        <div class="col-md-10">
          <%= a.text_field :given_name, class: "form-control"  %>
        </div>
      </div>

      <div class="form-group">
        <%= a.label :family_name, 'Author Family Name', class: "col-md-2 control-label" %>
        <div class="col-md-10">
          <%= a.text_field :family_name, class: "form-control"  %>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :publication, class: "col-md-2 control-label" %>
      <div class="col-md-10">
        <%= f.text_field :publication, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :abstract, class: "col-md-2 control-label" %>
      <div class="col-md-10">
        <%= f.text_area :abstract, class: "form-control", rows: 8 %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :link, class: "col-md-2 control-label" %>
      <div class="col-md-10">
        <%= f.text_field :link, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :doi, class: "col-md-2 control-label"  %>
      <div class="col-md-10">
        <%= f.text_field :doi, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :pubmed_id, class: "col-md-2 control-label"  %>
      <div class="col-md-10">
        <%= f.text_field :pubmed_id, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :published_at, class: "col-md-2 control-label"  %>
      <div class="col-md-10">
        <%= f.date_select :published_at, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :tag_list, 'Tags (separated by commas)', class: "col-md-2 control-label"  %>
      <div class="col-md-10">
        <%= f.text_field :tag_list, value: paper.tag_list.join(","), class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :methodology_list, class: "col-md-2 control-label"  %>
      <div class="col-md-10">
        <% paper.valid_methodologies.each do |m|%>
          <label class= "checkbox-inline">
            <%= f.check_box :methodology_list, {multiple: true}, m, nil %>
            <%= m %>
          </label>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :bias_list, class: "col-md-2 control-label"  %>
      <div class="col-md-10">
        <% paper.valid_biases.each do |b|%>
          <label class= "checkbox-inline">
            <%= f.check_box :bias_list, {multiple: true}, b, nil %>
            <%= b %>
          </label>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit button_name, class: "btn btn-primary" %>
      </div>
    </div>

  </div>
<% end %>

app/views/papers/_links.html.erb
<% paper = reference.paper %>

<% if paper.doi.present? %>
  <li>DOI: <%= link_to paper.doi, "http://dx.doi.org/#{paper.doi}", target: '_blank' %></li>
<% end %>

<% if paper.pubmed_id.present? %>
  <li>Pubmed ID: <%= link_to paper.pubmed_id, "https://www.ncbi.nlm.nih.gov/pubmed/#{paper.pubmed_id}", target: '_blank' %></li>
<% end %>

<% if paper.links.any? %>
  <% paper.links.each do |l| %>
    <li>
      <%= link_to l.url, l.url, target: '_blank' %>
      <% if l.link_editable %>
        <%= link_to '',
          destroy_link_path(reference, l),
          class: 'btn-icon remove-button',
          data: { confirm: 'Are you want to delete this link?' },
          remote: true
        %>
      <% else %>
      <i> - imported</i>
      <% end %>
    </li>
  <% end %>
<% end %>
<%= render 'papers/links_form', paper: paper %>

app/views/papers/_metadata.html.erb
<%= paper.authors.map(&:full_name).join(', ') %>
<i>
  <%= content_tag(:span, "in #{paper.publication}", class: 'publication') if paper.publication.present? %>
  <%= "(#{paper.published_at})" if paper.published_at.present? %>
</i>

app/views/papers/_paper_detail_wells.html.erb
<div class="collapse paper-detail well" id="abstract-<%= reference.id %>">
  <%= render 'papers/abstract', reference: reference %>
</div>

<div class="collapse paper-detail well" id="details-<%= reference.id %>">
  Links:
  <ul class="links">
    <%= render 'links/links', reference: reference %>
  </ul>
</div>

<div class="paper-detail well collapse <%= "in" if show_comments %>" id="comments-<%= reference.id %>">
  <%= render 'references/comments', reference: reference %>
</div>

app/views/papers/_pubmed_search.erb
<% if @results && params[:list_id] == list_id%>
  <ul>
    <% @results['result']['uids'].each do |uid| %>
      <li>
        <b><%=@results['result'][uid]['title']%></b>
        </br>Source: <%=@results['result'][uid]['source']%>
        | Authors: <%=@results['result'][uid]['authors'].map {|author| author['name']}.join(", ")%>
      <%= form_tag({controller: "papers", action: "pubmed_select"}, method: "get") do %>
        <%= hidden_field_tag('list_id', list_id) %>
        <%= submit_tag("Select") %>
      <% end %>
      </li>  
    <%end%>
  </ul>  
<%else%>  
<%end%>  
<%= form_tag({controller: "papers", action: "pubmed_search"}, method: "get") do %>
  <%= label_tag(:search_term, "Search using Pubmed ID, DOI, or title, authors, or keywords") %>
  <%= hidden_field_tag('list_id', list_id) %>
  <%= text_field_tag(:search_term, params[:list_id] == list_id ? params[:search_term] : nil)  %>
  <%= submit_tag("Search") %>
<% end %>

app/views/papers/_sort_by.html.erb
<div class="btn-group btn-group-xs nav-button-group sort" role="group" aria-label="...">
  <%= link_to 'Votes', url_for(sort: 'votes'), class: "btn btn-default #{'active' unless params[:sort] == 'pub_date'}", role: "button" %>
  <%= link_to 'Publish Date', url_for(sort: 'pub_date'), class: "btn btn-default #{'active' if params[:sort] == 'pub_date'}", role: 'button'  %>
</div>

app/views/papers/_tablist.html.erb
<% paper = reference.paper %>

<ul class="nav nav-pills small" role="tablist">
  <li><%= link_to 'Abstract', '', "data-detail-id" => "abstract-#{reference.id}", class: "paper-detail-tab" %></li>
  <li><%= link_to 'Details', '', "data-detail-id" => "details-#{reference.id}", class: "paper-detail-tab" %></li>
  <li><%= render 'references/comments_tab', reference: reference %></li>
  <% if current_user %>
    <li>
      <%= form_for reference, method: :delete do |r| %>
        <%= r.text_field :id, value: reference.id, hidden: true %>
      <% end %>
      <% if reference.user == current_user || current_user.can_moderate?(reference.list) %>
        <%= link_to('Remove from list', {}, class: 'delete-reference text-danger') %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/papers/_tags.html.erb
<span class="tags-list">
  <% tags = paper.tag_list %>
  <% tags.each do |tag| %>
    <a class="btn btn-default btn-xs"><%= tag %></a>
  <% end %>
  <%= link_to (if tags.empty? then "add a tag" else "edit tags" end), '#', class: "add-tag" %>
</span>
<%=  render 'papers/tags_form', paper: paper %>

app/views/papers/_tags_form.html.erb
<div class="tags-form hidden">
  <%= form_for(paper, html: {class: 'form-inline'}) do |f| %>
    <div class="form-group col-md-12">
      <%= f.text_field :tag_list, value: paper.tag_list.join(","), placeholder: "No tags added yet...", class: "form-control input-sm" %>
      <%= f.submit 'Add tags', class: "btn btn-xs btn-primary" %>
      <%= link_to "cancel", '#', class: "cancel-add-tag link-btn" %>
    </div>
  <% end %>
  <i class='help-block'><small>Tags should be seperated by commas.</small></i>
</div>

app/views/papers/destroy_link.js.erb
linksList = "<%= escape_javascript(render('papers/links', reference: reference)) %>";
linksUL = $("#details-<%= reference.id %>").find('.links');

linksUL.html(linksList);

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form', paper: @paper, button_name: "Update Paper" %>

<%= link_to 'Show', @paper %> |

app/views/papers/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @paper.title %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @paper.authors.map(&:full_name).join(', ') %>
</p>

<p>
  <strong>Publication:</strong>
  <span class="publication"> <%= @paper.publication unless @paper.publication.nil? %></span>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @paper.abstract %>
</p>

<p>
  <strong>Link:</strong>
  <%= @paper.link %>
</p>

<p>
  <strong>DOI:</strong>
  <%= @paper.doi %>
</p>

<p>
  <strong>Pubmed ID:</strong>
  <%= @paper.pubmed_id %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @paper.published_at %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @paper.tag_list %>
</p>

<p>
  <strong>Methodologies:</strong>
  <%= @paper.methodology_list %>
</p>

<p>
  <strong>Biases:</strong>
  <%= @paper.bias_list %>
</p>
<%= link_to 'Edit', edit_paper_path(@paper) %> |