config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  get '/about' => 'static_pages#about'
  get '/.well-known/acme-challenge/:id' => 'static_pages#lets_encrypt'

  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :papers, only: [:show, :edit, :update] do
    resources :links, only: :destroy, shallow: true
  end

  resources :pins, only: [:create, :destroy]

  resources :lists, only: [:new, :create] do
    resources :references, only: [:show, :create, :destroy]
    resource :vote, controller: 'lists/votes', only: [:create, :destroy]
    resources :members, only: :destroy, controller: 'lists/members'
  end

  resources :references do
    resource :vote, controller: 'references/votes', only: [:create, :destroy]
  end

  resources :comments, only: [:create, :edit, :update, :destroy] do
    resource :vote, controller: 'comments/votes', only: [:create, :destroy]
  end

  scope ':username' do
    resources :lists, path: '/', except: [:new, :create], as: :user_lists, controller: 'users/lists'
    get ':user_list_id/:id' => 'references#show', as: :user_list_reference
  end

end

app/models/reference.rb
class Reference < ApplicationRecord
  has_many :comments, as: :commentable

  belongs_to :paper
  belongs_to :list
  belongs_to :user

  validates :paper, uniqueness: { scope: :list }
  accepts_nested_attributes_for :paper

  acts_as_votable
end

app/controllers/reference/votes_controller.rb
class Reference::VotesController < ApplicationController
  before_action :ensure_current_user

  def create
    current_user.likes Reference.find(votable_params[:id])

    redirect_to :back
  end

  def destroy
    current_user.unlike Reference.find(votable_params[:id])

    redirect_to :back
  end

  private
    def votable_params
      params.permit(:id)
    end
end

app/controllers/references/votes_controller.rb
class References::VotesController < ApplicationController
  before_action :ensure_current_user

  def create
    current_user.likes Reference.find(votable_params[:id])

    redirect_to :back
  end

  def destroy
    current_user.unlike Reference.find(votable_params[:id])

    redirect_to :back
  end

  private
    def votable_params
      params.permit(:id)
    end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :ensure_current_user, except: :show
  before_action :set_paper_locator, only: :create

  def show
    @reference = Reference.find(params[:id])
  end

  def create
    list = List.find(reference_params[:list_id])
    list_path = user_list_path(list.owner, list)

    unless list.accepts_public_contributions? || current_user.can_edit?(list)
      return redirect_back(fallback_location: list_path, alert: 'You must be a contributor to make changes to this list.')
    end

    return redirect_back(fallback_location: list_path, alert: @locator.errors.join(' ')) unless @locator.valid?

    if (paper = @locator.find_or_import_paper)
      if Reference.exists? list_id: list.id, paper_id: paper.id
        flash['notice'] = "'#{paper.title}' has already been added to this list"
      else
        Reference.create(list_id: list.id, paper_id: paper.id, user_id: current_user.id)
        flash['notice'] = "You added '#{paper.title}' to '#{list.name}'"
      end
    else
      logger.debug "No paper found for: #{paper_params.inspect}"
      flash['alert'] = "Couldn't find or import a paper with those parameters"
    end
    redirect_back(fallback_location: list_path)
  end

  def destroy
    reference = Reference.find(reference_params[:id])

    unless reference.user == current_user || current_user.can_moderate?(reference.list)
      return redirect_back(fallback_location: user_list_path(reference.list.owner, reference.list), alert: 'You do not have permission to moderate this list.')
    end

    reference.destroy

    respond_to do |format|
      format.html { redirect_to user_list_path(reference.list.owner, reference.list), notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def reference_params
      params.require(:reference).permit(
        :list_id, :paper_id, :id, paper: [:locator_id, :locator_type, :title])
    end

    def paper_params
      reference_params.fetch(:paper, nil)
    end

    def set_paper_locator
      locator_type, locator_id, paper_title = paper_params.values_at(:locator_type, :locator_id, :title)

      return redirect_to(:back, alert: "Identifier can't be blank.") if locator_id.blank?

      case locator_type
      when 'doi'
        @locator = DoiPaperLocator.new locator_id: locator_id
      when 'link'
        @locator = LinkPaperLocator.new locator_id: locator_id, paper_title: paper_title
      when 'pubmed'
        @locator = PubmedPaperLocator.new locator_id: locator_id
      else
        return redirect_to(:back, alert: 'Bad locator parameters')
      end
    end
end

app/controllers/users/references_controller.rb
class Users::ReferencesController < ApplicationController
  def show
    user = User.find_by username: params[:username]
    list = user.lists.find_by slug: params[:user_list_id]

    @reference = list.references.find_by id: params[:id]
    render 'references/show'
  end
end

app/views/references/_comments.html.erb
<% if current_user %>
  <%= render 'comments/form', comment: reference.comments.build, hidden: false %>
<% else %>
  <h4>
    <%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %> to comment
  </h4>
<% end %>

<div class="reference comments" data-commentable-id="<%= reference.id %>">
  <% reference.comments.order('cached_votes_up DESC, created_at ASC').each do |comment| %>
    <%= comments_tree_for comment.hash_tree, reference.list %>
  <% end %>
</div>

app/views/references/_comments_tab.html.erb
 <%
  comments_count = reference.comments.map {|c| c.self_and_descendants.length}.inject(0,&:+)
  display_count =  content_tag(:span, comments_count, id: "comments-count-#{reference.id}")
%>
<%= link_to comments_count.zero? ? "Comments" : "Comments(#{display_count})".html_safe, '', "data-detail-id" => "comments-#{reference.id}", class: " paper-detail-tab" %>

app/views/references/_reference.html.erb
<% paper = reference.paper %>
<% direct_link =
  if paper.doi.present?
    "http://dx.doi.org/#{paper.doi}"
  elsif paper.pubmed_id.present?
    "https://www.ncbi.nlm.nih.gov/pubmed/#{paper.pubmed_id}"
  else
    paper.links.first.url
  end
%>

<div class="row paper-show">
  <% if not show_comments %>
    <div class="col-md-1"><%= render 'votes/toggle_like', votable: reference %></div>
  <% end %>
  <div class="col-md-<%= show_comments ? 12 : 11 %>">
    <% if show_comments %>
      <%= yield(:paper_title) %>
    <% else %>
      <h4 class="paper-title">
        <%= link_to paper.title, direct_link, target: '_blank' %>
      </h4>
    <% end %>

    <div class='reference-metadata'>
      <%= render 'papers/metadata', paper: paper %>
      <%= render 'papers/tags', paper: paper %>
    </div>

    <div class="reference-detail">
      <%= link_to 'permalink', user_list_reference_path(reference.list.user, reference.list, reference) %>
       - contributed by <%= link_to reference.user.username, user_lists_path(reference.user) %>
    </div>

    <%= render 'papers/tablist', reference: reference %>
    <%= render 'papers/paper_detail_wells', reference: reference, show_comments: show_comments %>

  </div>
</div>

app/views/references/show.html.erb
<% content_for :paper_title do %>
  <h1>
    <%= link_to @reference.paper.title, @reference %>
    <small>contributed by <%= link_to @reference.user.username, user_lists_path(@reference.user) %></small>
  </h1>
  <p>Referenced in <%= link_to @reference.list.name, user_list_path(@reference.list.owner, @reference.list) %></p>
<% end %>

<%= render 'references/reference', reference: @reference, show_comments: true %>